# Generated by Django 5.0.1 on 2024-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='items',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='type',
            field=models.CharField(choices=[('truck', 'Truck'), ('push_cart', 'Push Cart')], default='truck', max_length=31),
        ),
    ]
